name: endonerf
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - pip
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2021.5.30
  - cmake=3.29.4
  - freeglut=3.2.2
  - freetype=2.12.1
  - icu=69.1
  - intel-openmp=2024.2.1
  - jasper=2.0.33
  - jpeg=9e
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=8.9.1
  - libdeflate=1.14
  - libexpat=2.6.4
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.5.3
  - libpng=1.6.39
  - libprotobuf=3.16.0
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libuv=1.49.2
  - libwebp-base=1.3.0
  - libxml2=2.10.4
  - libzlib=1.2.13
  - mkl=2024.2.2
  - numpy=1.19.5
  - opencv=4.5.3
  - openssl=1.1.1w
  - pthreads-win32=2.9.1
  - py-opencv=4.5.3
  - python=3.6.13
  - python_abi=3.6
  - pywinpty=1.1.4
  - qt=5.12.9
  - setuptools=58.0.4
  - sqlite=3.45.3
  - tbb=2021.9.0
  - ucrt=10.0.22621.0
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.37.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==1.4.0
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - async-generator==1.10
      - attrs==22.2.0
      - babel==2.11.0
      - backcall==0.2.0
      - bleach==4.1.0
      - cachetools==4.2.4
      - cffi==1.15.1
      - charset-normalizer==2.0.12
      - colorama==0.4.5
      - comm==0.1.4
      - configargparse==1.7
      - contextvars==2.4
      - cycler==0.11.0
      - dataclasses==0.8
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - entrypoints==0.4
      - google-auth==2.22.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.48.2
      - idna==3.10
      - imageio==2.15.0
      - imageio-ffmpeg==0.5.1
      - immutables==0.19
      - importlib-metadata==4.8.3
      - importlib-resources==5.4.0
      - ipykernel==5.5.6
      - ipython==7.16.3
      - ipython-genutils==0.2.0
      - ipywidgets==7.8.5
      - jedi==0.17.2
      - jinja2==3.0.3
      - json5==0.9.16
      - jsonschema==3.2.0
      - jupyter==1.1.1
      - jupyter-client==7.1.2
      - jupyter-console==6.4.3
      - jupyter-core==4.9.2
      - jupyter-packaging==0.10.6
      - jupyter-server==1.13.1
      - jupyterlab==3.2.9
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.10.3
      - jupyterlab-widgets==1.1.11
      - kiwisolver==1.3.1
      - lpips==0.1.4
      - markdown==3.3.7
      - markupsafe==2.0.1
      - matplotlib==3.3.4
      - mistune==0.8.4
      - nbclassic==0.3.5
      - nbclient==0.5.9
      - nbconvert==6.0.7
      - nbformat==5.1.3
      - nest-asyncio==1.6.0
      - notebook==6.4.10
      - oauthlib==3.2.2
      - open3d==0.15.1
      - packaging==21.3
      - pandocfilters==1.5.1
      - parso==0.7.1
      - pickleshare==0.7.5
      - pillow==8.4.0
      - pip==21.3.1
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.36
      - protobuf==3.19.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygments==2.14.0
      - pymcubes==0.1.4
      - pyparsing==3.1.4
      - pyrsistent==0.18.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pywin32==305
      - pyzmq==25.1.2
      - requests==2.27.1
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scipy==1.5.4
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.2.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.12.1
      - testpath==0.6.0
      - tomlkit==0.11.6
      - torch==1.10.2
      - torchsearchsorted==1.1
      - torchvision==0.11.3
      - tornado==6.1
      - tqdm==4.64.1
      - traitlets==4.3.3
      - trimesh==3.23.5
      - typing-extensions==4.1.1
      - urllib3==1.26.20
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.3.1
      - werkzeug==2.0.3
      - widgetsnbextension==3.6.10
      - zipp==3.6.0
